#!/bin/bash
cd /home/ec2-user/javaapp
/opt/tomcat/bin/shutdown.sh
rm -rf /opt/tomcat/webapps/SpringClientServer/
rm -rf /opt/tomcat/webapps/SpringClientServer.war
mv /home/ec2-user/javaapp/SpringClientServer.war /opt/tomcat/webapps/
/opt/tomcat/bin/startup.sh

