#!/bin/bash
cd /home/ec2-user/javaapp
sudo /opt/tomcat/bin/shutdown.sh
rm -rf /opt/tomcat/webapps/SpringClientServer/
mv /home/ec2-user/javaapp/SpringClientServer.war /opt/tomcat/webapps/
sudo /opt/tomcat/bin/startup.sh

